CREATE DATABASE RENTAL_SYSTEM;

USE RENTAL_SYSTEM;

CREATE TABLE USERS(
    UID INT AUTO_INCREMENT PRIMARY KEY,
    UNAME VARCHAR(100) NOT NULL UNIQUE,
    UEMAIL VARCHAR(100) NOT NULL UNIQUE,
    UPASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE ITEMS(
    IID INT AUTO_INCREMENT PRIMARY KEY,
    INAME VARCHAR(100) NOT NULL,
UID INT, 
    CATEGORY VARCHAR(100),
    RENT_PER_DAY DECIMAL(10,2) NOT NULL,
    PENALTY_PER_DAY DECIMAL(10,2) NOT NULL,
    IS_AVAILABLE TINYINT(1) DEFAULT 1,

    FOREIGN KEY (UID) REFERENCES USERS(UID)
);

CREATE TABLE RENTALS(
    RID INT AUTO_INCREMENT PRIMARY KEY,
UID INT,
    IID INT,
    RENT_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    RETURN_DATE DATE NULL,
    TOTAL_COST DECIMAL(10,2) DEFAULT 0,
    PENALTY DECIMAL(10,2) DEFAULT 0,
    STATUS ENUM('ONGOING','RETURNED') DEFAULT 'ONGOING',

    FOREIGN KEY (UID) REFERENCES USERS(UID),
    FOREIGN KEY (IID) REFERENCES ITEMS(IID)
);